version: v1
plugins:
  # Generate structs for protocol buffer definition
  - plugin: buf.build/protocolbuffers/go:v1.31.0
    out: ../__generated__/
    opt:
      - paths=source_relative
  # Generate gRPC stubs
  - plugin: buf.build/grpc/go:v1.3.0
    out: ../__generated__/
    opt:
      - paths=source_relative
  # Generate gRPC HTTP Gateway
  - plugin: buf.build/grpc-ecosystem/gateway:v2.16.2
    out: ../__generated__/
    opt:
      - paths=source_relative
  # Generate OpenAPI
  - plugin: buf.build/grpc-ecosystem/openapiv2:v2.16.2
    out: ../__generated__/
