version: "3.8"
services:
  watcher-service:
    build:
      context: ./services/watcher-service
    environment:
      - MONITORED_DIR=${IMAGES_DIR}
      - UPLOAD_URL=${UPLOAD_URL}
    volumes:
      - ${IMAGES_DIR}:/images
  imaginary:
    build: https://github.com/h2non/imaginary.git
    command: -mount /editted
    environment:
      - PORT=9000
      - IMAGINARY_VERSION=${IMAGINARY_VERSION}
    ports:
      - "9000:9000"
    volumes:
      - ${IMAGES_DIR}:/images
