version: "3.8"
services:
  grpc-server:
    build:
      dockerfile: server.Dockerfile
    environment:
      - PORT=9000
    ports:
      - "9000:9000"
    volumes:
      # Mount the directory which will contain images to be processed
      - ${IMAGES_DIR}:/images
  http-gateway:
    build:
      dockerfile: gateway.Dockerfile
    environment:
      - PORT=8080
      - GRPC_SERV_ADDR=grpc-server:9000
    ports:
      - "8080:8080"
  imaginary:
    build: https://github.com/h2non/imaginary.git
    command: -mount /editted
    environment:
      - PORT=9000
      - IMAGINARY_VERSION=${IMAGINARY_VERSION}
    ports:
      - "9000:9000"
    volumes:
      - ${IMAGES_DIR}:/images

