version: v1
plugins:
  - plugin: go
    out: ../__generated__/go
    opt: paths=source_relative
  - plugin: go-grpc
    out: ../__generated__/go
    opt: paths=source_relative,require_unimplemented_servers=false
  - plugin: grpc-gateway
    out: ../__generated__/go
    opt: paths=source_relative
