req-animal:
	grpcurl -plaintext -d '{"image":{"path":"test/images/animal.jpg"}}' localhost:9090 motif_service.v1.MotifService/get_b_box

req-obj:
	grpcurl -plaintext -d '{"image":{"path":"test/images/object.jpg"}}' localhost:9090 motif_service.v1.MotifService/get_b_box

req-human:
	grpcurl -plaintext -d '{"image":{"path":"test/images/human.jpg"}}' localhost:9090 motif_service.v1.MotifService/get_b_box