# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/motif_service/v1/b_box_service.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'services/motif_service/v1/b_box_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from messages.base64_image_dto.v1 import base64_image_dto_pb2 as messages_dot_base64__image__dto_dot_v1_dot_base64__image__dto__pb2
from messages.image_dto.v1 import image_dto_pb2 as messages_dot_image__dto_dot_v1_dot_image__dto__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-services/motif_service/v1/b_box_service.proto\x12\x19services.motif_service.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x33messages/base64_image_dto/v1/base64_image_dto.proto\x1a%messages/image_dto/v1/image_dto.proto\"S\n\x07\x42\x42oxDto\x12\x0c\n\x01x\x18\x01 \x01(\x05R\x01x\x12\x0c\n\x01y\x18\x02 \x01(\x05R\x01y\x12\x14\n\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n\x06height\x18\x04 \x01(\x05R\x06height\"N\n\x0eGetBBoxRequest\x12<\n\x05image\x18\x01 \x01(\x0b\x32&.shared.messages.image_dto.v1.ImageDtoR\x05image\"S\n\x13GetBBoxDebugRequest\x12<\n\x05image\x18\x01 \x01(\x0b\x32&.shared.messages.image_dto.v1.ImageDtoR\x05image\"J\n\x0fGetBBoxResponse\x12\x37\n\x05\x62_box\x18\x01 \x01(\x0b\x32\".services.motif_service.v1.BBoxDtoR\x04\x62\x42ox\"a\n\x14GetBBoxDebugResponse\x12I\n\x05image\x18\x01 \x01(\x0b\x32\x33.shared.messages.base64_image_dto.v1.Base64ImageDtoR\x05image2\x96\x02\n\x0b\x42\x42oxService\x12w\n\tget_b_box\x12).services.motif_service.v1.GetBBoxRequest\x1a*.services.motif_service.v1.GetBBoxResponse\"\x13\x82\xd3\xe4\x93\x02\r\"\x08/v1/bbox:\x01*\x12\x8d\x01\n\x0fget_b_box_debug\x12..services.motif_service.v1.GetBBoxDebugRequest\x1a/.services.motif_service.v1.GetBBoxDebugResponse\"\x19\x82\xd3\xe4\x93\x02\x13\"\x0e/v1/bbox/debug:\x01*B\xbe\x02\n\x1d\x63om.services.motif_service.v1B\x10\x42\x42oxServiceProtoP\x01Z\x88\x01github.com/nico-i/photo-ops/services/motif_service_gateway/src/infrastructure/__generated__/go/services/motif_service/v1;motif_servicev1\xa2\x02\x03SMX\xaa\x02\x18Services.MotifService.V1\xca\x02\x18Services\\MotifService\\V1\xe2\x02$Services\\MotifService\\V1\\GPBMetadata\xea\x02\x1aServices::MotifService::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.motif_service.v1.b_box_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\035com.services.motif_service.v1B\020BBoxServiceProtoP\001Z\210\001github.com/nico-i/photo-ops/services/motif_service_gateway/src/infrastructure/__generated__/go/services/motif_service/v1;motif_servicev1\242\002\003SMX\252\002\030Services.MotifService.V1\312\002\030Services\\MotifService\\V1\342\002$Services\\MotifService\\V1\\GPBMetadata\352\002\032Services::MotifService::V1'
  _globals['_BBOXSERVICE'].methods_by_name['get_b_box']._loaded_options = None
  _globals['_BBOXSERVICE'].methods_by_name['get_b_box']._serialized_options = b'\202\323\344\223\002\r\"\010/v1/bbox:\001*'
  _globals['_BBOXSERVICE'].methods_by_name['get_b_box_debug']._loaded_options = None
  _globals['_BBOXSERVICE'].methods_by_name['get_b_box_debug']._serialized_options = b'\202\323\344\223\002\023\"\016/v1/bbox/debug:\001*'
  _globals['_BBOXDTO']._serialized_start=198
  _globals['_BBOXDTO']._serialized_end=281
  _globals['_GETBBOXREQUEST']._serialized_start=283
  _globals['_GETBBOXREQUEST']._serialized_end=361
  _globals['_GETBBOXDEBUGREQUEST']._serialized_start=363
  _globals['_GETBBOXDEBUGREQUEST']._serialized_end=446
  _globals['_GETBBOXRESPONSE']._serialized_start=448
  _globals['_GETBBOXRESPONSE']._serialized_end=522
  _globals['_GETBBOXDEBUGRESPONSE']._serialized_start=524
  _globals['_GETBBOXDEBUGRESPONSE']._serialized_end=621
  _globals['_BBOXSERVICE']._serialized_start=624
  _globals['_BBOXSERVICE']._serialized_end=902
# @@protoc_insertion_point(module_scope)
