# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/metadata_service/v1/metadata_service.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'services/metadata_service/v1/metadata_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from messages.image_dto.v1 import image_dto_pb2 as messages_dot_image__dto_dot_v1_dot_image__dto__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3services/metadata_service/v1/metadata_service.proto\x12\x13metadata_service.v1\x1a\x1cgoogle/api/annotations.proto\x1a%messages/image_dto/v1/image_dto.proto\"\x90\x01\n\x15UpdateIPTCDataRequest\x12<\n\x05image\x18\x01 \x01(\x0b\x32&.shared.messages.image_dto.v1.ImageDtoR\x05image\x12\x18\n\x07\x63\x61ption\x18\x02 \x01(\tR\x07\x63\x61ption\x12\x1f\n\x0bhashtag_csv\x18\x03 \x01(\tR\nhashtagCsv\"\x18\n\x16UpdateIPTCDataResponse2\x94\x01\n\x0fMetaDataService\x12\x80\x01\n\x10update_iptc_data\x12*.metadata_service.v1.UpdateIPTCDataRequest\x1a+.metadata_service.v1.UpdateIPTCDataResponse\"\x13\x82\xd3\xe4\x93\x02\r\"\x08/v1/iptc:\x01*B\x83\x02\n\x17\x63om.metadata_service.v1B\x14MetadataServiceProtoP\x01Zigithub.com/nico-i/photo-ops/shared/go/__generated__/proto/services/metadata_service/v1;metadata_servicev1\xa2\x02\x03MXX\xaa\x02\x12MetadataService.V1\xca\x02\x12MetadataService\\V1\xe2\x02\x1eMetadataService\\V1\\GPBMetadata\xea\x02\x13MetadataService::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.metadata_service.v1.metadata_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027com.metadata_service.v1B\024MetadataServiceProtoP\001Zigithub.com/nico-i/photo-ops/shared/go/__generated__/proto/services/metadata_service/v1;metadata_servicev1\242\002\003MXX\252\002\022MetadataService.V1\312\002\022MetadataService\\V1\342\002\036MetadataService\\V1\\GPBMetadata\352\002\023MetadataService::V1'
  _globals['_METADATASERVICE'].methods_by_name['update_iptc_data']._loaded_options = None
  _globals['_METADATASERVICE'].methods_by_name['update_iptc_data']._serialized_options = b'\202\323\344\223\002\r\"\010/v1/iptc:\001*'
  _globals['_UPDATEIPTCDATAREQUEST']._serialized_start=146
  _globals['_UPDATEIPTCDATAREQUEST']._serialized_end=290
  _globals['_UPDATEIPTCDATARESPONSE']._serialized_start=292
  _globals['_UPDATEIPTCDATARESPONSE']._serialized_end=316
  _globals['_METADATASERVICE']._serialized_start=319
  _globals['_METADATASERVICE']._serialized_end=467
# @@protoc_insertion_point(module_scope)
