version: "3.8"
services:
  grpc-server:
    build:
      dockerfile: server.Dockerfile
    environment:
      - PORT=9000
    ports:
      - "9000:9000"
    volumes:
      # Mount the directory which will contain images to be processed
      - ${IMAGES_DIR}:/images
  http-gateway:
    build:
      dockerfile: gateway.Dockerfile
    environment:
      - PORT=8080
      - GRPC_SERV_ADDR=grpc-server:9000
    ports:
      - "8080:8080"
