# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: b_box.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'b_box.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62_box.proto\x12\x02v1\x1a\x1cgoogle/api/annotations.proto\"c\n\x08ImageDto\x12\x14\n\x04path\x18\x01 \x01(\tH\x00R\x04path\x12\x37\n\x0c\x62\x61se64_image\x18\x02 \x01(\x0b\x32\x12.v1.Base64ImageDtoH\x00R\x0b\x62\x61se64ImageB\x08\n\x06source\"$\n\x0e\x42\x61se64ImageDto\x12\x12\n\x04\x64\x61ta\x18\x01 \x01(\tR\x04\x64\x61ta\"S\n\x07\x42\x42oxDto\x12\x0c\n\x01x\x18\x01 \x01(\x05R\x01x\x12\x0c\n\x01y\x18\x02 \x01(\x05R\x01y\x12\x14\n\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n\x06height\x18\x04 \x01(\x05R\x06height\"4\n\x0eGetBBoxRequest\x12\"\n\x05image\x18\x01 \x01(\x0b\x32\x0c.v1.ImageDtoR\x05image\"9\n\x13GetBBoxDebugRequest\x12\"\n\x05image\x18\x01 \x01(\x0b\x32\x0c.v1.ImageDtoR\x05image\"3\n\x0fGetBBoxResponse\x12 \n\x05\x62_box\x18\x01 \x01(\x0b\x32\x0b.v1.BBoxDtoR\x04\x62\x42ox\"@\n\x14GetBBoxDebugResponse\x12(\n\x05image\x18\x01 \x01(\x0b\x32\x12.v1.Base64ImageDtoR\x05image2\xc5\x01\n\x0b\x42\x42oxService\x12O\n\tget_b_box\x12\x12.v1.GetBBoxRequest\x1a\x13.v1.GetBBoxResponse\"\x19\x82\xd3\xe4\x93\x02\x13\"\x0e/v1/bbox-local:\x01*\x12\x65\n\x0fget_b_box_debug\x12\x17.v1.GetBBoxDebugRequest\x1a\x18.v1.GetBBoxDebugResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\"\x14/v1/bbox-local/debug:\x01*B;\n\x06\x63om.v1B\tBBoxProtoP\x01\xa2\x02\x03VXX\xaa\x02\x02V1\xca\x02\x02V1\xe2\x02\x0eV1\\GPBMetadata\xea\x02\x02V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'b_box_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\006com.v1B\tBBoxProtoP\001\242\002\003VXX\252\002\002V1\312\002\002V1\342\002\016V1\\GPBMetadata\352\002\002V1'
  _globals['_BBOXSERVICE'].methods_by_name['get_b_box']._loaded_options = None
  _globals['_BBOXSERVICE'].methods_by_name['get_b_box']._serialized_options = b'\202\323\344\223\002\023\"\016/v1/bbox-local:\001*'
  _globals['_BBOXSERVICE'].methods_by_name['get_b_box_debug']._loaded_options = None
  _globals['_BBOXSERVICE'].methods_by_name['get_b_box_debug']._serialized_options = b'\202\323\344\223\002\031\"\024/v1/bbox-local/debug:\001*'
  _globals['_IMAGEDTO']._serialized_start=49
  _globals['_IMAGEDTO']._serialized_end=148
  _globals['_BASE64IMAGEDTO']._serialized_start=150
  _globals['_BASE64IMAGEDTO']._serialized_end=186
  _globals['_BBOXDTO']._serialized_start=188
  _globals['_BBOXDTO']._serialized_end=271
  _globals['_GETBBOXREQUEST']._serialized_start=273
  _globals['_GETBBOXREQUEST']._serialized_end=325
  _globals['_GETBBOXDEBUGREQUEST']._serialized_start=327
  _globals['_GETBBOXDEBUGREQUEST']._serialized_end=384
  _globals['_GETBBOXRESPONSE']._serialized_start=386
  _globals['_GETBBOXRESPONSE']._serialized_end=437
  _globals['_GETBBOXDEBUGRESPONSE']._serialized_start=439
  _globals['_GETBBOXDEBUGRESPONSE']._serialized_end=503
  _globals['_BBOXSERVICE']._serialized_start=506
  _globals['_BBOXSERVICE']._serialized_end=703
# @@protoc_insertion_point(module_scope)
