# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from v1 import caption_service_pb2 as v1_dot_caption__service__pb2


class CaptionServiceStub(object):
    """Service to handle all image captioning operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_caption = channel.unary_unary(
                '/caption_service.v1.CaptionService/get_caption',
                request_serializer=v1_dot_caption__service__pb2.GetCaptionRequest.SerializeToString,
                response_deserializer=v1_dot_caption__service__pb2.GetCaptionResponse.FromString,
                _registered_method=True)


class CaptionServiceServicer(object):
    """Service to handle all image captioning operations
    """

    def get_caption(self, request, context):
        """Get caption for an image
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CaptionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_caption': grpc.unary_unary_rpc_method_handler(
                    servicer.get_caption,
                    request_deserializer=v1_dot_caption__service__pb2.GetCaptionRequest.FromString,
                    response_serializer=v1_dot_caption__service__pb2.GetCaptionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'caption_service.v1.CaptionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('caption_service.v1.CaptionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CaptionService(object):
    """Service to handle all image captioning operations
    """

    @staticmethod
    def get_caption(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caption_service.v1.CaptionService/get_caption',
            v1_dot_caption__service__pb2.GetCaptionRequest.SerializeToString,
            v1_dot_caption__service__pb2.GetCaptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
