# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/caption_service.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'v1/caption_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from messages.v1 import image_dto_pb2 as messages_dot_v1_dot_image__dto__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18v1/caption_service.proto\x12\x12\x63\x61ption_service.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bmessages/v1/image_dto.proto\"G\n\x11GetCaptionRequest\x12\x32\n\x05image\x18\x01 \x01(\x0b\x32\x1c.shared.messages.v1.ImageDtoR\x05image\".\n\x12GetCaptionResponse\x12\x18\n\x07\x63\x61ption\x18\x01 \x01(\tR\x07\x63\x61ption2\x86\x01\n\x0e\x43\x61ptionService\x12t\n\x0bget_caption\x12%.caption_service.v1.GetCaptionRequest\x1a&.caption_service.v1.GetCaptionResponse\"\x16\x82\xd3\xe4\x93\x02\x10\"\x0b/v1/caption:\x01*b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.caption_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CAPTIONSERVICE'].methods_by_name['get_caption']._loaded_options = None
  _globals['_CAPTIONSERVICE'].methods_by_name['get_caption']._serialized_options = b'\202\323\344\223\002\020\"\013/v1/caption:\001*'
  _globals['_GETCAPTIONREQUEST']._serialized_start=107
  _globals['_GETCAPTIONREQUEST']._serialized_end=178
  _globals['_GETCAPTIONRESPONSE']._serialized_start=180
  _globals['_GETCAPTIONRESPONSE']._serialized_end=226
  _globals['_CAPTIONSERVICE']._serialized_start=229
  _globals['_CAPTIONSERVICE']._serialized_end=363
# @@protoc_insertion_point(module_scope)
