# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages/rect_dto/v1/rect_dto.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'messages/rect_dto/v1/rect_dto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#messages/rect_dto/v1/rect_dto.proto\x12\x1bshared.messages.rect_dto.v1\"S\n\x07RectDto\x12\x0c\n\x01x\x18\x01 \x01(\x05R\x01x\x12\x0c\n\x01y\x18\x02 \x01(\x05R\x01y\x12\x14\n\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n\x06height\x18\x04 \x01(\x05R\x06heightB\x95\x02\n\x1f\x63om.shared.messages.rect_dto.v1B\x0cRectDtoProtoP\x01ZYgithub.com/nico-i/photo-ops/shared/go/__generated__/proto/messages/rect_dto/v1;rect_dtov1\xa2\x02\x03SMR\xaa\x02\x1aShared.Messages.RectDto.V1\xca\x02\x1aShared\\Messages\\RectDto\\V1\xe2\x02&Shared\\Messages\\RectDto\\V1\\GPBMetadata\xea\x02\x1dShared::Messages::RectDto::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages.rect_dto.v1.rect_dto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\037com.shared.messages.rect_dto.v1B\014RectDtoProtoP\001ZYgithub.com/nico-i/photo-ops/shared/go/__generated__/proto/messages/rect_dto/v1;rect_dtov1\242\002\003SMR\252\002\032Shared.Messages.RectDto.V1\312\002\032Shared\\Messages\\RectDto\\V1\342\002&Shared\\Messages\\RectDto\\V1\\GPBMetadata\352\002\035Shared::Messages::RectDto::V1'
  _globals['_RECTDTO']._serialized_start=68
  _globals['_RECTDTO']._serialized_end=151
# @@protoc_insertion_point(module_scope)
